#! /usr/bin/bash

optimize=""
config_path="$PROJECT_HOME/data/single_run_example.json"
output_path="output"
dry=""
runs=1
verbose=""
visualize=0
skip_run=false
use_logy=""
while [[ $# -ne 0 ]]; do
    case "$1" in
        --release|-r)
            optimize="--config=optimized"
            shift 1
            ;;
        --dry)
            dry="--dry"
            shift 1
            ;;
        --verbose|-v)
            verbose="--verbose"
            shift 1
            ;;
        --config)
            config_path="$PROJECT_HOME/$2"
            shift 2
            ;;
        --runs)
            runs=$2
            shift 2
            ;;
        --skip_run)
            skip_run=true
            shift 1
            ;;
        -o|--output)
            output_path="$2"
            shift 2
            ;;
        --visualize)
            visualize=1
            shift 1
            ;;
        --use_logy)
            use_logy="--use_logy"
            shift 1
            ;;
        *)
            echo "Unrecognized command! $1"
            echo "./run [--release|-r] [--config $config_path] [--output|-o $output_path] [--dry] [--runs $runs] [--visualize]"
            exit 1
            ;;
    esac
done

set -xe

if [[ $skip_run == false ]]; then
    bazel run //:main $optimize -- --config $config_path $dry --runs $runs -o $output_path $verbose
fi

if [[ $visualize == 1 ]]; then
    bazel run //tools/cpp_viz:main --config=optimized -- $PROJECT_HOME/$output_path
    # uv run python $PROJECT_HOME/tools/visualization/plot_timeseries_data.py --output_dir $output_path --save_dir "$output_path/visualization" $use_logy
fi