#! /usr/bin/bash

target="cached"
if [[ $# == 1 ]]; then
	target="$1"
	for t in $(ls $PROJECT_HOME/tests/*$target*.cpp); do 
		bazel test //tests:$(basename $t ".cpp") --config=unit_testing -j 6 --test_env=PROJECT_HOME=.
	done
else
	bazel test //tests:$target --config=unit_testing -j 6 --test_env=PROJECT_HOME=.
fi
