// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/protos/AnnualInflationConfig.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_src_2fprotos_2fAnnualInflationConfig_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_src_2fprotos_2fAnnualInflationConfig_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "src/protos/Event.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_src_2fprotos_2fAnnualInflationConfig_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_src_2fprotos_2fAnnualInflationConfig_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_src_2fprotos_2fAnnualInflationConfig_2eproto;
class AnnualInflationConfig;
struct AnnualInflationConfigDefaultTypeInternal;
extern AnnualInflationConfigDefaultTypeInternal _AnnualInflationConfig_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::AnnualInflationConfig* Arena::CreateMaybeMessage<::AnnualInflationConfig>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class AnnualInflationConfig final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:AnnualInflationConfig) */ {
 public:
  inline AnnualInflationConfig() : AnnualInflationConfig(nullptr) {}
  ~AnnualInflationConfig() override;
  explicit PROTOBUF_CONSTEXPR AnnualInflationConfig(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AnnualInflationConfig(const AnnualInflationConfig& from);
  AnnualInflationConfig(AnnualInflationConfig&& from) noexcept
    : AnnualInflationConfig() {
    *this = ::std::move(from);
  }

  inline AnnualInflationConfig& operator=(const AnnualInflationConfig& from) {
    CopyFrom(from);
    return *this;
  }
  inline AnnualInflationConfig& operator=(AnnualInflationConfig&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AnnualInflationConfig& default_instance() {
    return *internal_default_instance();
  }
  static inline const AnnualInflationConfig* internal_default_instance() {
    return reinterpret_cast<const AnnualInflationConfig*>(
               &_AnnualInflationConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(AnnualInflationConfig& a, AnnualInflationConfig& b) {
    a.Swap(&b);
  }
  inline void Swap(AnnualInflationConfig* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AnnualInflationConfig* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AnnualInflationConfig* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<AnnualInflationConfig>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const AnnualInflationConfig& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const AnnualInflationConfig& from) {
    AnnualInflationConfig::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AnnualInflationConfig* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "AnnualInflationConfig";
  }
  protected:
  explicit AnnualInflationConfig(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDeflationEventFieldNumber = 2,
    kInflationEventFieldNumber = 3,
    kRateFieldNumber = 1,
  };
  // .Event deflation_event = 2;
  bool has_deflation_event() const;
  private:
  bool _internal_has_deflation_event() const;
  public:
  void clear_deflation_event();
  const ::Event& deflation_event() const;
  PROTOBUF_NODISCARD ::Event* release_deflation_event();
  ::Event* mutable_deflation_event();
  void set_allocated_deflation_event(::Event* deflation_event);
  private:
  const ::Event& _internal_deflation_event() const;
  ::Event* _internal_mutable_deflation_event();
  public:
  void unsafe_arena_set_allocated_deflation_event(
      ::Event* deflation_event);
  ::Event* unsafe_arena_release_deflation_event();

  // .Event inflation_event = 3;
  bool has_inflation_event() const;
  private:
  bool _internal_has_inflation_event() const;
  public:
  void clear_inflation_event();
  const ::Event& inflation_event() const;
  PROTOBUF_NODISCARD ::Event* release_inflation_event();
  ::Event* mutable_inflation_event();
  void set_allocated_inflation_event(::Event* inflation_event);
  private:
  const ::Event& _internal_inflation_event() const;
  ::Event* _internal_mutable_inflation_event();
  public:
  void unsafe_arena_set_allocated_inflation_event(
      ::Event* inflation_event);
  ::Event* unsafe_arena_release_inflation_event();

  // double rate = 1;
  void clear_rate();
  double rate() const;
  void set_rate(double value);
  private:
  double _internal_rate() const;
  void _internal_set_rate(double value);
  public:

  // @@protoc_insertion_point(class_scope:AnnualInflationConfig)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::Event* deflation_event_;
    ::Event* inflation_event_;
    double rate_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_src_2fprotos_2fAnnualInflationConfig_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// AnnualInflationConfig

// double rate = 1;
inline void AnnualInflationConfig::clear_rate() {
  _impl_.rate_ = 0;
}
inline double AnnualInflationConfig::_internal_rate() const {
  return _impl_.rate_;
}
inline double AnnualInflationConfig::rate() const {
  // @@protoc_insertion_point(field_get:AnnualInflationConfig.rate)
  return _internal_rate();
}
inline void AnnualInflationConfig::_internal_set_rate(double value) {
  
  _impl_.rate_ = value;
}
inline void AnnualInflationConfig::set_rate(double value) {
  _internal_set_rate(value);
  // @@protoc_insertion_point(field_set:AnnualInflationConfig.rate)
}

// .Event deflation_event = 2;
inline bool AnnualInflationConfig::_internal_has_deflation_event() const {
  return this != internal_default_instance() && _impl_.deflation_event_ != nullptr;
}
inline bool AnnualInflationConfig::has_deflation_event() const {
  return _internal_has_deflation_event();
}
inline const ::Event& AnnualInflationConfig::_internal_deflation_event() const {
  const ::Event* p = _impl_.deflation_event_;
  return p != nullptr ? *p : reinterpret_cast<const ::Event&>(
      ::_Event_default_instance_);
}
inline const ::Event& AnnualInflationConfig::deflation_event() const {
  // @@protoc_insertion_point(field_get:AnnualInflationConfig.deflation_event)
  return _internal_deflation_event();
}
inline void AnnualInflationConfig::unsafe_arena_set_allocated_deflation_event(
    ::Event* deflation_event) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.deflation_event_);
  }
  _impl_.deflation_event_ = deflation_event;
  if (deflation_event) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:AnnualInflationConfig.deflation_event)
}
inline ::Event* AnnualInflationConfig::release_deflation_event() {
  
  ::Event* temp = _impl_.deflation_event_;
  _impl_.deflation_event_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::Event* AnnualInflationConfig::unsafe_arena_release_deflation_event() {
  // @@protoc_insertion_point(field_release:AnnualInflationConfig.deflation_event)
  
  ::Event* temp = _impl_.deflation_event_;
  _impl_.deflation_event_ = nullptr;
  return temp;
}
inline ::Event* AnnualInflationConfig::_internal_mutable_deflation_event() {
  
  if (_impl_.deflation_event_ == nullptr) {
    auto* p = CreateMaybeMessage<::Event>(GetArenaForAllocation());
    _impl_.deflation_event_ = p;
  }
  return _impl_.deflation_event_;
}
inline ::Event* AnnualInflationConfig::mutable_deflation_event() {
  ::Event* _msg = _internal_mutable_deflation_event();
  // @@protoc_insertion_point(field_mutable:AnnualInflationConfig.deflation_event)
  return _msg;
}
inline void AnnualInflationConfig::set_allocated_deflation_event(::Event* deflation_event) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.deflation_event_);
  }
  if (deflation_event) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(deflation_event));
    if (message_arena != submessage_arena) {
      deflation_event = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, deflation_event, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.deflation_event_ = deflation_event;
  // @@protoc_insertion_point(field_set_allocated:AnnualInflationConfig.deflation_event)
}

// .Event inflation_event = 3;
inline bool AnnualInflationConfig::_internal_has_inflation_event() const {
  return this != internal_default_instance() && _impl_.inflation_event_ != nullptr;
}
inline bool AnnualInflationConfig::has_inflation_event() const {
  return _internal_has_inflation_event();
}
inline const ::Event& AnnualInflationConfig::_internal_inflation_event() const {
  const ::Event* p = _impl_.inflation_event_;
  return p != nullptr ? *p : reinterpret_cast<const ::Event&>(
      ::_Event_default_instance_);
}
inline const ::Event& AnnualInflationConfig::inflation_event() const {
  // @@protoc_insertion_point(field_get:AnnualInflationConfig.inflation_event)
  return _internal_inflation_event();
}
inline void AnnualInflationConfig::unsafe_arena_set_allocated_inflation_event(
    ::Event* inflation_event) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.inflation_event_);
  }
  _impl_.inflation_event_ = inflation_event;
  if (inflation_event) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:AnnualInflationConfig.inflation_event)
}
inline ::Event* AnnualInflationConfig::release_inflation_event() {
  
  ::Event* temp = _impl_.inflation_event_;
  _impl_.inflation_event_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::Event* AnnualInflationConfig::unsafe_arena_release_inflation_event() {
  // @@protoc_insertion_point(field_release:AnnualInflationConfig.inflation_event)
  
  ::Event* temp = _impl_.inflation_event_;
  _impl_.inflation_event_ = nullptr;
  return temp;
}
inline ::Event* AnnualInflationConfig::_internal_mutable_inflation_event() {
  
  if (_impl_.inflation_event_ == nullptr) {
    auto* p = CreateMaybeMessage<::Event>(GetArenaForAllocation());
    _impl_.inflation_event_ = p;
  }
  return _impl_.inflation_event_;
}
inline ::Event* AnnualInflationConfig::mutable_inflation_event() {
  ::Event* _msg = _internal_mutable_inflation_event();
  // @@protoc_insertion_point(field_mutable:AnnualInflationConfig.inflation_event)
  return _msg;
}
inline void AnnualInflationConfig::set_allocated_inflation_event(::Event* inflation_event) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.inflation_event_);
  }
  if (inflation_event) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(inflation_event));
    if (message_arena != submessage_arena) {
      inflation_event = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, inflation_event, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.inflation_event_ = inflation_event;
  // @@protoc_insertion_point(field_set_allocated:AnnualInflationConfig.inflation_event)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_src_2fprotos_2fAnnualInflationConfig_2eproto
