// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/protos/AnnualInflationConfig.proto

#include "src/protos/AnnualInflationConfig.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

PROTOBUF_CONSTEXPR AnnualInflationConfig::AnnualInflationConfig(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.deflation_event_)*/nullptr
  , /*decltype(_impl_.inflation_event_)*/nullptr
  , /*decltype(_impl_.rate_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct AnnualInflationConfigDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AnnualInflationConfigDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~AnnualInflationConfigDefaultTypeInternal() {}
  union {
    AnnualInflationConfig _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AnnualInflationConfigDefaultTypeInternal _AnnualInflationConfig_default_instance_;
static ::_pb::Metadata file_level_metadata_src_2fprotos_2fAnnualInflationConfig_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_src_2fprotos_2fAnnualInflationConfig_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_src_2fprotos_2fAnnualInflationConfig_2eproto = nullptr;

const uint32_t TableStruct_src_2fprotos_2fAnnualInflationConfig_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::AnnualInflationConfig, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::AnnualInflationConfig, _impl_.rate_),
  PROTOBUF_FIELD_OFFSET(::AnnualInflationConfig, _impl_.deflation_event_),
  PROTOBUF_FIELD_OFFSET(::AnnualInflationConfig, _impl_.inflation_event_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::AnnualInflationConfig)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::_AnnualInflationConfig_default_instance_._instance,
};

const char descriptor_table_protodef_src_2fprotos_2fAnnualInflationConfig_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n&src/protos/AnnualInflationConfig.proto"
  "\032\026src/protos/Event.proto\"g\n\025AnnualInflat"
  "ionConfig\022\014\n\004rate\030\001 \001(\001\022\037\n\017deflation_eve"
  "nt\030\002 \001(\0132\006.Event\022\037\n\017inflation_event\030\003 \001("
  "\0132\006.Eventb\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_src_2fprotos_2fAnnualInflationConfig_2eproto_deps[1] = {
  &::descriptor_table_src_2fprotos_2fEvent_2eproto,
};
static ::_pbi::once_flag descriptor_table_src_2fprotos_2fAnnualInflationConfig_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_src_2fprotos_2fAnnualInflationConfig_2eproto = {
    false, false, 177, descriptor_table_protodef_src_2fprotos_2fAnnualInflationConfig_2eproto,
    "src/protos/AnnualInflationConfig.proto",
    &descriptor_table_src_2fprotos_2fAnnualInflationConfig_2eproto_once, descriptor_table_src_2fprotos_2fAnnualInflationConfig_2eproto_deps, 1, 1,
    schemas, file_default_instances, TableStruct_src_2fprotos_2fAnnualInflationConfig_2eproto::offsets,
    file_level_metadata_src_2fprotos_2fAnnualInflationConfig_2eproto, file_level_enum_descriptors_src_2fprotos_2fAnnualInflationConfig_2eproto,
    file_level_service_descriptors_src_2fprotos_2fAnnualInflationConfig_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_src_2fprotos_2fAnnualInflationConfig_2eproto_getter() {
  return &descriptor_table_src_2fprotos_2fAnnualInflationConfig_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_src_2fprotos_2fAnnualInflationConfig_2eproto(&descriptor_table_src_2fprotos_2fAnnualInflationConfig_2eproto);

// ===================================================================

class AnnualInflationConfig::_Internal {
 public:
  static const ::Event& deflation_event(const AnnualInflationConfig* msg);
  static const ::Event& inflation_event(const AnnualInflationConfig* msg);
};

const ::Event&
AnnualInflationConfig::_Internal::deflation_event(const AnnualInflationConfig* msg) {
  return *msg->_impl_.deflation_event_;
}
const ::Event&
AnnualInflationConfig::_Internal::inflation_event(const AnnualInflationConfig* msg) {
  return *msg->_impl_.inflation_event_;
}
void AnnualInflationConfig::clear_deflation_event() {
  if (GetArenaForAllocation() == nullptr && _impl_.deflation_event_ != nullptr) {
    delete _impl_.deflation_event_;
  }
  _impl_.deflation_event_ = nullptr;
}
void AnnualInflationConfig::clear_inflation_event() {
  if (GetArenaForAllocation() == nullptr && _impl_.inflation_event_ != nullptr) {
    delete _impl_.inflation_event_;
  }
  _impl_.inflation_event_ = nullptr;
}
AnnualInflationConfig::AnnualInflationConfig(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:AnnualInflationConfig)
}
AnnualInflationConfig::AnnualInflationConfig(const AnnualInflationConfig& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  AnnualInflationConfig* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.deflation_event_){nullptr}
    , decltype(_impl_.inflation_event_){nullptr}
    , decltype(_impl_.rate_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_deflation_event()) {
    _this->_impl_.deflation_event_ = new ::Event(*from._impl_.deflation_event_);
  }
  if (from._internal_has_inflation_event()) {
    _this->_impl_.inflation_event_ = new ::Event(*from._impl_.inflation_event_);
  }
  _this->_impl_.rate_ = from._impl_.rate_;
  // @@protoc_insertion_point(copy_constructor:AnnualInflationConfig)
}

inline void AnnualInflationConfig::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.deflation_event_){nullptr}
    , decltype(_impl_.inflation_event_){nullptr}
    , decltype(_impl_.rate_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

AnnualInflationConfig::~AnnualInflationConfig() {
  // @@protoc_insertion_point(destructor:AnnualInflationConfig)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void AnnualInflationConfig::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.deflation_event_;
  if (this != internal_default_instance()) delete _impl_.inflation_event_;
}

void AnnualInflationConfig::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void AnnualInflationConfig::Clear() {
// @@protoc_insertion_point(message_clear_start:AnnualInflationConfig)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.deflation_event_ != nullptr) {
    delete _impl_.deflation_event_;
  }
  _impl_.deflation_event_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.inflation_event_ != nullptr) {
    delete _impl_.inflation_event_;
  }
  _impl_.inflation_event_ = nullptr;
  _impl_.rate_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* AnnualInflationConfig::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // double rate = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 9)) {
          _impl_.rate_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // .Event deflation_event = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_deflation_event(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .Event inflation_event = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_inflation_event(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* AnnualInflationConfig::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:AnnualInflationConfig)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // double rate = 1;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_rate = this->_internal_rate();
  uint64_t raw_rate;
  memcpy(&raw_rate, &tmp_rate, sizeof(tmp_rate));
  if (raw_rate != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(1, this->_internal_rate(), target);
  }

  // .Event deflation_event = 2;
  if (this->_internal_has_deflation_event()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::deflation_event(this),
        _Internal::deflation_event(this).GetCachedSize(), target, stream);
  }

  // .Event inflation_event = 3;
  if (this->_internal_has_inflation_event()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, _Internal::inflation_event(this),
        _Internal::inflation_event(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:AnnualInflationConfig)
  return target;
}

size_t AnnualInflationConfig::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:AnnualInflationConfig)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .Event deflation_event = 2;
  if (this->_internal_has_deflation_event()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.deflation_event_);
  }

  // .Event inflation_event = 3;
  if (this->_internal_has_inflation_event()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.inflation_event_);
  }

  // double rate = 1;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_rate = this->_internal_rate();
  uint64_t raw_rate;
  memcpy(&raw_rate, &tmp_rate, sizeof(tmp_rate));
  if (raw_rate != 0) {
    total_size += 1 + 8;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData AnnualInflationConfig::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    AnnualInflationConfig::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*AnnualInflationConfig::GetClassData() const { return &_class_data_; }


void AnnualInflationConfig::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<AnnualInflationConfig*>(&to_msg);
  auto& from = static_cast<const AnnualInflationConfig&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:AnnualInflationConfig)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_deflation_event()) {
    _this->_internal_mutable_deflation_event()->::Event::MergeFrom(
        from._internal_deflation_event());
  }
  if (from._internal_has_inflation_event()) {
    _this->_internal_mutable_inflation_event()->::Event::MergeFrom(
        from._internal_inflation_event());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_rate = from._internal_rate();
  uint64_t raw_rate;
  memcpy(&raw_rate, &tmp_rate, sizeof(tmp_rate));
  if (raw_rate != 0) {
    _this->_internal_set_rate(from._internal_rate());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void AnnualInflationConfig::CopyFrom(const AnnualInflationConfig& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:AnnualInflationConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AnnualInflationConfig::IsInitialized() const {
  return true;
}

void AnnualInflationConfig::InternalSwap(AnnualInflationConfig* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(AnnualInflationConfig, _impl_.rate_)
      + sizeof(AnnualInflationConfig::_impl_.rate_)
      - PROTOBUF_FIELD_OFFSET(AnnualInflationConfig, _impl_.deflation_event_)>(
          reinterpret_cast<char*>(&_impl_.deflation_event_),
          reinterpret_cast<char*>(&other->_impl_.deflation_event_));
}

::PROTOBUF_NAMESPACE_ID::Metadata AnnualInflationConfig::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_src_2fprotos_2fAnnualInflationConfig_2eproto_getter, &descriptor_table_src_2fprotos_2fAnnualInflationConfig_2eproto_once,
      file_level_metadata_src_2fprotos_2fAnnualInflationConfig_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::AnnualInflationConfig*
Arena::CreateMaybeMessage< ::AnnualInflationConfig >(Arena* arena) {
  return Arena::CreateMessageInternal< ::AnnualInflationConfig >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
