// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/protos/Event.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_src_2fprotos_2fEvent_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_src_2fprotos_2fEvent_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_src_2fprotos_2fEvent_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_src_2fprotos_2fEvent_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_src_2fprotos_2fEvent_2eproto;
class Event;
struct EventDefaultTypeInternal;
extern EventDefaultTypeInternal _Event_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::Event* Arena::CreateMaybeMessage<::Event>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class Event final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Event) */ {
 public:
  inline Event() : Event(nullptr) {}
  ~Event() override;
  explicit PROTOBUF_CONSTEXPR Event(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Event(const Event& from);
  Event(Event&& from) noexcept
    : Event() {
    *this = ::std::move(from);
  }

  inline Event& operator=(const Event& from) {
    CopyFrom(from);
    return *this;
  }
  inline Event& operator=(Event&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Event& default_instance() {
    return *internal_default_instance();
  }
  static inline const Event* internal_default_instance() {
    return reinterpret_cast<const Event*>(
               &_Event_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Event& a, Event& b) {
    a.Swap(&b);
  }
  inline void Swap(Event* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Event* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Event* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Event>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Event& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Event& from) {
    Event::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Event* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Event";
  }
  protected:
  explicit Event(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kCooldownFieldNumber = 1,
    kDurationFieldNumber = 2,
    kEventValFieldNumber = 3,
    kKnockdownFieldNumber = 4,
    kProbabilityFieldNumber = 5,
    kRngSeedFieldNumber = 6,
    kScalingFactorFieldNumber = 7,
  };
  // uint64 cooldown = 1;
  void clear_cooldown();
  uint64_t cooldown() const;
  void set_cooldown(uint64_t value);
  private:
  uint64_t _internal_cooldown() const;
  void _internal_set_cooldown(uint64_t value);
  public:

  // uint64 duration = 2;
  void clear_duration();
  uint64_t duration() const;
  void set_duration(uint64_t value);
  private:
  uint64_t _internal_duration() const;
  void _internal_set_duration(uint64_t value);
  public:

  // double event_val = 3;
  void clear_event_val();
  double event_val() const;
  void set_event_val(double value);
  private:
  double _internal_event_val() const;
  void _internal_set_event_val(double value);
  public:

  // double knockdown = 4;
  void clear_knockdown();
  double knockdown() const;
  void set_knockdown(double value);
  private:
  double _internal_knockdown() const;
  void _internal_set_knockdown(double value);
  public:

  // double probability = 5;
  void clear_probability();
  double probability() const;
  void set_probability(double value);
  private:
  double _internal_probability() const;
  void _internal_set_probability(double value);
  public:

  // uint64 rng_seed = 6;
  void clear_rng_seed();
  uint64_t rng_seed() const;
  void set_rng_seed(uint64_t value);
  private:
  uint64_t _internal_rng_seed() const;
  void _internal_set_rng_seed(uint64_t value);
  public:

  // double scaling_factor = 7;
  void clear_scaling_factor();
  double scaling_factor() const;
  void set_scaling_factor(double value);
  private:
  double _internal_scaling_factor() const;
  void _internal_set_scaling_factor(double value);
  public:

  // @@protoc_insertion_point(class_scope:Event)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint64_t cooldown_;
    uint64_t duration_;
    double event_val_;
    double knockdown_;
    double probability_;
    uint64_t rng_seed_;
    double scaling_factor_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_src_2fprotos_2fEvent_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Event

// uint64 cooldown = 1;
inline void Event::clear_cooldown() {
  _impl_.cooldown_ = uint64_t{0u};
}
inline uint64_t Event::_internal_cooldown() const {
  return _impl_.cooldown_;
}
inline uint64_t Event::cooldown() const {
  // @@protoc_insertion_point(field_get:Event.cooldown)
  return _internal_cooldown();
}
inline void Event::_internal_set_cooldown(uint64_t value) {
  
  _impl_.cooldown_ = value;
}
inline void Event::set_cooldown(uint64_t value) {
  _internal_set_cooldown(value);
  // @@protoc_insertion_point(field_set:Event.cooldown)
}

// uint64 duration = 2;
inline void Event::clear_duration() {
  _impl_.duration_ = uint64_t{0u};
}
inline uint64_t Event::_internal_duration() const {
  return _impl_.duration_;
}
inline uint64_t Event::duration() const {
  // @@protoc_insertion_point(field_get:Event.duration)
  return _internal_duration();
}
inline void Event::_internal_set_duration(uint64_t value) {
  
  _impl_.duration_ = value;
}
inline void Event::set_duration(uint64_t value) {
  _internal_set_duration(value);
  // @@protoc_insertion_point(field_set:Event.duration)
}

// double event_val = 3;
inline void Event::clear_event_val() {
  _impl_.event_val_ = 0;
}
inline double Event::_internal_event_val() const {
  return _impl_.event_val_;
}
inline double Event::event_val() const {
  // @@protoc_insertion_point(field_get:Event.event_val)
  return _internal_event_val();
}
inline void Event::_internal_set_event_val(double value) {
  
  _impl_.event_val_ = value;
}
inline void Event::set_event_val(double value) {
  _internal_set_event_val(value);
  // @@protoc_insertion_point(field_set:Event.event_val)
}

// double knockdown = 4;
inline void Event::clear_knockdown() {
  _impl_.knockdown_ = 0;
}
inline double Event::_internal_knockdown() const {
  return _impl_.knockdown_;
}
inline double Event::knockdown() const {
  // @@protoc_insertion_point(field_get:Event.knockdown)
  return _internal_knockdown();
}
inline void Event::_internal_set_knockdown(double value) {
  
  _impl_.knockdown_ = value;
}
inline void Event::set_knockdown(double value) {
  _internal_set_knockdown(value);
  // @@protoc_insertion_point(field_set:Event.knockdown)
}

// double probability = 5;
inline void Event::clear_probability() {
  _impl_.probability_ = 0;
}
inline double Event::_internal_probability() const {
  return _impl_.probability_;
}
inline double Event::probability() const {
  // @@protoc_insertion_point(field_get:Event.probability)
  return _internal_probability();
}
inline void Event::_internal_set_probability(double value) {
  
  _impl_.probability_ = value;
}
inline void Event::set_probability(double value) {
  _internal_set_probability(value);
  // @@protoc_insertion_point(field_set:Event.probability)
}

// uint64 rng_seed = 6;
inline void Event::clear_rng_seed() {
  _impl_.rng_seed_ = uint64_t{0u};
}
inline uint64_t Event::_internal_rng_seed() const {
  return _impl_.rng_seed_;
}
inline uint64_t Event::rng_seed() const {
  // @@protoc_insertion_point(field_get:Event.rng_seed)
  return _internal_rng_seed();
}
inline void Event::_internal_set_rng_seed(uint64_t value) {
  
  _impl_.rng_seed_ = value;
}
inline void Event::set_rng_seed(uint64_t value) {
  _internal_set_rng_seed(value);
  // @@protoc_insertion_point(field_set:Event.rng_seed)
}

// double scaling_factor = 7;
inline void Event::clear_scaling_factor() {
  _impl_.scaling_factor_ = 0;
}
inline double Event::_internal_scaling_factor() const {
  return _impl_.scaling_factor_;
}
inline double Event::scaling_factor() const {
  // @@protoc_insertion_point(field_get:Event.scaling_factor)
  return _internal_scaling_factor();
}
inline void Event::_internal_set_scaling_factor(double value) {
  
  _impl_.scaling_factor_ = value;
}
inline void Event::set_scaling_factor(double value) {
  _internal_set_scaling_factor(value);
  // @@protoc_insertion_point(field_set:Event.scaling_factor)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_src_2fprotos_2fEvent_2eproto
