// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/protos/Event.proto

#include "src/protos/Event.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

PROTOBUF_CONSTEXPR Event::Event(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.cooldown_)*/uint64_t{0u}
  , /*decltype(_impl_.duration_)*/uint64_t{0u}
  , /*decltype(_impl_.event_val_)*/0
  , /*decltype(_impl_.knockdown_)*/0
  , /*decltype(_impl_.probability_)*/0
  , /*decltype(_impl_.rng_seed_)*/uint64_t{0u}
  , /*decltype(_impl_.scaling_factor_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct EventDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EventDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~EventDefaultTypeInternal() {}
  union {
    Event _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EventDefaultTypeInternal _Event_default_instance_;
static ::_pb::Metadata file_level_metadata_src_2fprotos_2fEvent_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_src_2fprotos_2fEvent_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_src_2fprotos_2fEvent_2eproto = nullptr;

const uint32_t TableStruct_src_2fprotos_2fEvent_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Event, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Event, _impl_.cooldown_),
  PROTOBUF_FIELD_OFFSET(::Event, _impl_.duration_),
  PROTOBUF_FIELD_OFFSET(::Event, _impl_.event_val_),
  PROTOBUF_FIELD_OFFSET(::Event, _impl_.knockdown_),
  PROTOBUF_FIELD_OFFSET(::Event, _impl_.probability_),
  PROTOBUF_FIELD_OFFSET(::Event, _impl_.rng_seed_),
  PROTOBUF_FIELD_OFFSET(::Event, _impl_.scaling_factor_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::Event)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::_Event_default_instance_._instance,
};

const char descriptor_table_protodef_src_2fprotos_2fEvent_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\026src/protos/Event.proto\"\220\001\n\005Event\022\020\n\010co"
  "oldown\030\001 \001(\004\022\020\n\010duration\030\002 \001(\004\022\021\n\tevent_"
  "val\030\003 \001(\001\022\021\n\tknockdown\030\004 \001(\001\022\023\n\013probabil"
  "ity\030\005 \001(\001\022\020\n\010rng_seed\030\006 \001(\004\022\026\n\016scaling_f"
  "actor\030\007 \001(\001b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_src_2fprotos_2fEvent_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_src_2fprotos_2fEvent_2eproto = {
    false, false, 179, descriptor_table_protodef_src_2fprotos_2fEvent_2eproto,
    "src/protos/Event.proto",
    &descriptor_table_src_2fprotos_2fEvent_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_src_2fprotos_2fEvent_2eproto::offsets,
    file_level_metadata_src_2fprotos_2fEvent_2eproto, file_level_enum_descriptors_src_2fprotos_2fEvent_2eproto,
    file_level_service_descriptors_src_2fprotos_2fEvent_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_src_2fprotos_2fEvent_2eproto_getter() {
  return &descriptor_table_src_2fprotos_2fEvent_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_src_2fprotos_2fEvent_2eproto(&descriptor_table_src_2fprotos_2fEvent_2eproto);

// ===================================================================

class Event::_Internal {
 public:
};

Event::Event(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Event)
}
Event::Event(const Event& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Event* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.cooldown_){}
    , decltype(_impl_.duration_){}
    , decltype(_impl_.event_val_){}
    , decltype(_impl_.knockdown_){}
    , decltype(_impl_.probability_){}
    , decltype(_impl_.rng_seed_){}
    , decltype(_impl_.scaling_factor_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.cooldown_, &from._impl_.cooldown_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.scaling_factor_) -
    reinterpret_cast<char*>(&_impl_.cooldown_)) + sizeof(_impl_.scaling_factor_));
  // @@protoc_insertion_point(copy_constructor:Event)
}

inline void Event::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.cooldown_){uint64_t{0u}}
    , decltype(_impl_.duration_){uint64_t{0u}}
    , decltype(_impl_.event_val_){0}
    , decltype(_impl_.knockdown_){0}
    , decltype(_impl_.probability_){0}
    , decltype(_impl_.rng_seed_){uint64_t{0u}}
    , decltype(_impl_.scaling_factor_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

Event::~Event() {
  // @@protoc_insertion_point(destructor:Event)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Event::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void Event::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Event::Clear() {
// @@protoc_insertion_point(message_clear_start:Event)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.cooldown_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.scaling_factor_) -
      reinterpret_cast<char*>(&_impl_.cooldown_)) + sizeof(_impl_.scaling_factor_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Event::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint64 cooldown = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.cooldown_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint64 duration = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.duration_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // double event_val = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 25)) {
          _impl_.event_val_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // double knockdown = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 33)) {
          _impl_.knockdown_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // double probability = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 41)) {
          _impl_.probability_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // uint64 rng_seed = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 48)) {
          _impl_.rng_seed_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // double scaling_factor = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 57)) {
          _impl_.scaling_factor_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Event::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Event)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 cooldown = 1;
  if (this->_internal_cooldown() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(1, this->_internal_cooldown(), target);
  }

  // uint64 duration = 2;
  if (this->_internal_duration() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(2, this->_internal_duration(), target);
  }

  // double event_val = 3;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_event_val = this->_internal_event_val();
  uint64_t raw_event_val;
  memcpy(&raw_event_val, &tmp_event_val, sizeof(tmp_event_val));
  if (raw_event_val != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(3, this->_internal_event_val(), target);
  }

  // double knockdown = 4;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_knockdown = this->_internal_knockdown();
  uint64_t raw_knockdown;
  memcpy(&raw_knockdown, &tmp_knockdown, sizeof(tmp_knockdown));
  if (raw_knockdown != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(4, this->_internal_knockdown(), target);
  }

  // double probability = 5;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_probability = this->_internal_probability();
  uint64_t raw_probability;
  memcpy(&raw_probability, &tmp_probability, sizeof(tmp_probability));
  if (raw_probability != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(5, this->_internal_probability(), target);
  }

  // uint64 rng_seed = 6;
  if (this->_internal_rng_seed() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(6, this->_internal_rng_seed(), target);
  }

  // double scaling_factor = 7;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_scaling_factor = this->_internal_scaling_factor();
  uint64_t raw_scaling_factor;
  memcpy(&raw_scaling_factor, &tmp_scaling_factor, sizeof(tmp_scaling_factor));
  if (raw_scaling_factor != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(7, this->_internal_scaling_factor(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Event)
  return target;
}

size_t Event::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Event)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint64 cooldown = 1;
  if (this->_internal_cooldown() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_cooldown());
  }

  // uint64 duration = 2;
  if (this->_internal_duration() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_duration());
  }

  // double event_val = 3;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_event_val = this->_internal_event_val();
  uint64_t raw_event_val;
  memcpy(&raw_event_val, &tmp_event_val, sizeof(tmp_event_val));
  if (raw_event_val != 0) {
    total_size += 1 + 8;
  }

  // double knockdown = 4;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_knockdown = this->_internal_knockdown();
  uint64_t raw_knockdown;
  memcpy(&raw_knockdown, &tmp_knockdown, sizeof(tmp_knockdown));
  if (raw_knockdown != 0) {
    total_size += 1 + 8;
  }

  // double probability = 5;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_probability = this->_internal_probability();
  uint64_t raw_probability;
  memcpy(&raw_probability, &tmp_probability, sizeof(tmp_probability));
  if (raw_probability != 0) {
    total_size += 1 + 8;
  }

  // uint64 rng_seed = 6;
  if (this->_internal_rng_seed() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_rng_seed());
  }

  // double scaling_factor = 7;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_scaling_factor = this->_internal_scaling_factor();
  uint64_t raw_scaling_factor;
  memcpy(&raw_scaling_factor, &tmp_scaling_factor, sizeof(tmp_scaling_factor));
  if (raw_scaling_factor != 0) {
    total_size += 1 + 8;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Event::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Event::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Event::GetClassData() const { return &_class_data_; }


void Event::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Event*>(&to_msg);
  auto& from = static_cast<const Event&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Event)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_cooldown() != 0) {
    _this->_internal_set_cooldown(from._internal_cooldown());
  }
  if (from._internal_duration() != 0) {
    _this->_internal_set_duration(from._internal_duration());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_event_val = from._internal_event_val();
  uint64_t raw_event_val;
  memcpy(&raw_event_val, &tmp_event_val, sizeof(tmp_event_val));
  if (raw_event_val != 0) {
    _this->_internal_set_event_val(from._internal_event_val());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_knockdown = from._internal_knockdown();
  uint64_t raw_knockdown;
  memcpy(&raw_knockdown, &tmp_knockdown, sizeof(tmp_knockdown));
  if (raw_knockdown != 0) {
    _this->_internal_set_knockdown(from._internal_knockdown());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_probability = from._internal_probability();
  uint64_t raw_probability;
  memcpy(&raw_probability, &tmp_probability, sizeof(tmp_probability));
  if (raw_probability != 0) {
    _this->_internal_set_probability(from._internal_probability());
  }
  if (from._internal_rng_seed() != 0) {
    _this->_internal_set_rng_seed(from._internal_rng_seed());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_scaling_factor = from._internal_scaling_factor();
  uint64_t raw_scaling_factor;
  memcpy(&raw_scaling_factor, &tmp_scaling_factor, sizeof(tmp_scaling_factor));
  if (raw_scaling_factor != 0) {
    _this->_internal_set_scaling_factor(from._internal_scaling_factor());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Event::CopyFrom(const Event& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Event)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Event::IsInitialized() const {
  return true;
}

void Event::InternalSwap(Event* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Event, _impl_.scaling_factor_)
      + sizeof(Event::_impl_.scaling_factor_)
      - PROTOBUF_FIELD_OFFSET(Event, _impl_.cooldown_)>(
          reinterpret_cast<char*>(&_impl_.cooldown_),
          reinterpret_cast<char*>(&other->_impl_.cooldown_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Event::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_src_2fprotos_2fEvent_2eproto_getter, &descriptor_table_src_2fprotos_2fEvent_2eproto_once,
      file_level_metadata_src_2fprotos_2fEvent_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::Event*
Arena::CreateMaybeMessage< ::Event >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Event >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
