// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/protos/Money.proto

#include "src/protos/Money.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

PROTOBUF_CONSTEXPR Money::Money(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.dollars_)*/uint64_t{0u}
  , /*decltype(_impl_.cents_)*/uint64_t{0u}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct MoneyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MoneyDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~MoneyDefaultTypeInternal() {}
  union {
    Money _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MoneyDefaultTypeInternal _Money_default_instance_;
static ::_pb::Metadata file_level_metadata_src_2fprotos_2fMoney_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_src_2fprotos_2fMoney_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_src_2fprotos_2fMoney_2eproto = nullptr;

const uint32_t TableStruct_src_2fprotos_2fMoney_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Money, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Money, _impl_.dollars_),
  PROTOBUF_FIELD_OFFSET(::Money, _impl_.cents_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::Money)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::_Money_default_instance_._instance,
};

const char descriptor_table_protodef_src_2fprotos_2fMoney_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\026src/protos/Money.proto\"\'\n\005Money\022\017\n\007dol"
  "lars\030\001 \001(\004\022\r\n\005cents\030\002 \001(\004b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_src_2fprotos_2fMoney_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_src_2fprotos_2fMoney_2eproto = {
    false, false, 73, descriptor_table_protodef_src_2fprotos_2fMoney_2eproto,
    "src/protos/Money.proto",
    &descriptor_table_src_2fprotos_2fMoney_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_src_2fprotos_2fMoney_2eproto::offsets,
    file_level_metadata_src_2fprotos_2fMoney_2eproto, file_level_enum_descriptors_src_2fprotos_2fMoney_2eproto,
    file_level_service_descriptors_src_2fprotos_2fMoney_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_src_2fprotos_2fMoney_2eproto_getter() {
  return &descriptor_table_src_2fprotos_2fMoney_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_src_2fprotos_2fMoney_2eproto(&descriptor_table_src_2fprotos_2fMoney_2eproto);

// ===================================================================

class Money::_Internal {
 public:
};

Money::Money(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Money)
}
Money::Money(const Money& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Money* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.dollars_){}
    , decltype(_impl_.cents_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.dollars_, &from._impl_.dollars_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.cents_) -
    reinterpret_cast<char*>(&_impl_.dollars_)) + sizeof(_impl_.cents_));
  // @@protoc_insertion_point(copy_constructor:Money)
}

inline void Money::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.dollars_){uint64_t{0u}}
    , decltype(_impl_.cents_){uint64_t{0u}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

Money::~Money() {
  // @@protoc_insertion_point(destructor:Money)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Money::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void Money::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Money::Clear() {
// @@protoc_insertion_point(message_clear_start:Money)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.dollars_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.cents_) -
      reinterpret_cast<char*>(&_impl_.dollars_)) + sizeof(_impl_.cents_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Money::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint64 dollars = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.dollars_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint64 cents = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.cents_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Money::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Money)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 dollars = 1;
  if (this->_internal_dollars() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(1, this->_internal_dollars(), target);
  }

  // uint64 cents = 2;
  if (this->_internal_cents() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(2, this->_internal_cents(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Money)
  return target;
}

size_t Money::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Money)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint64 dollars = 1;
  if (this->_internal_dollars() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_dollars());
  }

  // uint64 cents = 2;
  if (this->_internal_cents() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_cents());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Money::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Money::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Money::GetClassData() const { return &_class_data_; }


void Money::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Money*>(&to_msg);
  auto& from = static_cast<const Money&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Money)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_dollars() != 0) {
    _this->_internal_set_dollars(from._internal_dollars());
  }
  if (from._internal_cents() != 0) {
    _this->_internal_set_cents(from._internal_cents());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Money::CopyFrom(const Money& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Money)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Money::IsInitialized() const {
  return true;
}

void Money::InternalSwap(Money* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Money, _impl_.cents_)
      + sizeof(Money::_impl_.cents_)
      - PROTOBUF_FIELD_OFFSET(Money, _impl_.dollars_)>(
          reinterpret_cast<char*>(&_impl_.dollars_),
          reinterpret_cast<char*>(&other->_impl_.dollars_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Money::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_src_2fprotos_2fMoney_2eproto_getter, &descriptor_table_src_2fprotos_2fMoney_2eproto_once,
      file_level_metadata_src_2fprotos_2fMoney_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::Money*
Arena::CreateMaybeMessage< ::Money >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Money >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
