// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/protos/PersonConfig.proto

#include "src/protos/PersonConfig.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

PROTOBUF_CONSTEXPR PersonConfig::PersonConfig(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.desired_cash_on_hand_)*/nullptr
  , /*decltype(_impl_.income_until_retirement_)*/nullptr
  , /*decltype(_impl_.initial_yearly_expenses_)*/nullptr
  , /*decltype(_impl_.medical_event_)*/nullptr
  , /*decltype(_impl_.starting_money_)*/nullptr
  , /*decltype(_impl_.current_age_)*/uint64_t{0u}
  , /*decltype(_impl_.death_age_)*/uint64_t{0u}
  , /*decltype(_impl_.retirement_age_)*/uint64_t{0u}
  , /*decltype(_impl_.stock_bond_ratio_)*/0
  , /*decltype(_impl_.yearly_raise_percent_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct PersonConfigDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PersonConfigDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PersonConfigDefaultTypeInternal() {}
  union {
    PersonConfig _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PersonConfigDefaultTypeInternal _PersonConfig_default_instance_;
static ::_pb::Metadata file_level_metadata_src_2fprotos_2fPersonConfig_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_src_2fprotos_2fPersonConfig_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_src_2fprotos_2fPersonConfig_2eproto = nullptr;

const uint32_t TableStruct_src_2fprotos_2fPersonConfig_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::PersonConfig, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::PersonConfig, _impl_.current_age_),
  PROTOBUF_FIELD_OFFSET(::PersonConfig, _impl_.death_age_),
  PROTOBUF_FIELD_OFFSET(::PersonConfig, _impl_.desired_cash_on_hand_),
  PROTOBUF_FIELD_OFFSET(::PersonConfig, _impl_.income_until_retirement_),
  PROTOBUF_FIELD_OFFSET(::PersonConfig, _impl_.initial_yearly_expenses_),
  PROTOBUF_FIELD_OFFSET(::PersonConfig, _impl_.medical_event_),
  PROTOBUF_FIELD_OFFSET(::PersonConfig, _impl_.retirement_age_),
  PROTOBUF_FIELD_OFFSET(::PersonConfig, _impl_.starting_money_),
  PROTOBUF_FIELD_OFFSET(::PersonConfig, _impl_.stock_bond_ratio_),
  PROTOBUF_FIELD_OFFSET(::PersonConfig, _impl_.yearly_raise_percent_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::PersonConfig)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::_PersonConfig_default_instance_._instance,
};

const char descriptor_table_protodef_src_2fprotos_2fPersonConfig_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\035src/protos/PersonConfig.proto\032\026src/pro"
  "tos/Money.proto\032\026src/protos/Event.proto\""
  "\275\002\n\014PersonConfig\022\023\n\013current_age\030\001 \001(\004\022\021\n"
  "\tdeath_age\030\002 \001(\004\022$\n\024desired_cash_on_hand"
  "\030\003 \001(\0132\006.Money\022\'\n\027income_until_retiremen"
  "t\030\004 \001(\0132\006.Money\022\'\n\027initial_yearly_expens"
  "es\030\005 \001(\0132\006.Money\022\035\n\rmedical_event\030\006 \001(\0132"
  "\006.Event\022\026\n\016retirement_age\030\007 \001(\004\022\036\n\016start"
  "ing_money\030\010 \001(\0132\006.Money\022\030\n\020stock_bond_ra"
  "tio\030\t \001(\001\022\034\n\024yearly_raise_percent\030\n \001(\001b"
  "\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_src_2fprotos_2fPersonConfig_2eproto_deps[2] = {
  &::descriptor_table_src_2fprotos_2fEvent_2eproto,
  &::descriptor_table_src_2fprotos_2fMoney_2eproto,
};
static ::_pbi::once_flag descriptor_table_src_2fprotos_2fPersonConfig_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_src_2fprotos_2fPersonConfig_2eproto = {
    false, false, 407, descriptor_table_protodef_src_2fprotos_2fPersonConfig_2eproto,
    "src/protos/PersonConfig.proto",
    &descriptor_table_src_2fprotos_2fPersonConfig_2eproto_once, descriptor_table_src_2fprotos_2fPersonConfig_2eproto_deps, 2, 1,
    schemas, file_default_instances, TableStruct_src_2fprotos_2fPersonConfig_2eproto::offsets,
    file_level_metadata_src_2fprotos_2fPersonConfig_2eproto, file_level_enum_descriptors_src_2fprotos_2fPersonConfig_2eproto,
    file_level_service_descriptors_src_2fprotos_2fPersonConfig_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_src_2fprotos_2fPersonConfig_2eproto_getter() {
  return &descriptor_table_src_2fprotos_2fPersonConfig_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_src_2fprotos_2fPersonConfig_2eproto(&descriptor_table_src_2fprotos_2fPersonConfig_2eproto);

// ===================================================================

class PersonConfig::_Internal {
 public:
  static const ::Money& desired_cash_on_hand(const PersonConfig* msg);
  static const ::Money& income_until_retirement(const PersonConfig* msg);
  static const ::Money& initial_yearly_expenses(const PersonConfig* msg);
  static const ::Event& medical_event(const PersonConfig* msg);
  static const ::Money& starting_money(const PersonConfig* msg);
};

const ::Money&
PersonConfig::_Internal::desired_cash_on_hand(const PersonConfig* msg) {
  return *msg->_impl_.desired_cash_on_hand_;
}
const ::Money&
PersonConfig::_Internal::income_until_retirement(const PersonConfig* msg) {
  return *msg->_impl_.income_until_retirement_;
}
const ::Money&
PersonConfig::_Internal::initial_yearly_expenses(const PersonConfig* msg) {
  return *msg->_impl_.initial_yearly_expenses_;
}
const ::Event&
PersonConfig::_Internal::medical_event(const PersonConfig* msg) {
  return *msg->_impl_.medical_event_;
}
const ::Money&
PersonConfig::_Internal::starting_money(const PersonConfig* msg) {
  return *msg->_impl_.starting_money_;
}
void PersonConfig::clear_desired_cash_on_hand() {
  if (GetArenaForAllocation() == nullptr && _impl_.desired_cash_on_hand_ != nullptr) {
    delete _impl_.desired_cash_on_hand_;
  }
  _impl_.desired_cash_on_hand_ = nullptr;
}
void PersonConfig::clear_income_until_retirement() {
  if (GetArenaForAllocation() == nullptr && _impl_.income_until_retirement_ != nullptr) {
    delete _impl_.income_until_retirement_;
  }
  _impl_.income_until_retirement_ = nullptr;
}
void PersonConfig::clear_initial_yearly_expenses() {
  if (GetArenaForAllocation() == nullptr && _impl_.initial_yearly_expenses_ != nullptr) {
    delete _impl_.initial_yearly_expenses_;
  }
  _impl_.initial_yearly_expenses_ = nullptr;
}
void PersonConfig::clear_medical_event() {
  if (GetArenaForAllocation() == nullptr && _impl_.medical_event_ != nullptr) {
    delete _impl_.medical_event_;
  }
  _impl_.medical_event_ = nullptr;
}
void PersonConfig::clear_starting_money() {
  if (GetArenaForAllocation() == nullptr && _impl_.starting_money_ != nullptr) {
    delete _impl_.starting_money_;
  }
  _impl_.starting_money_ = nullptr;
}
PersonConfig::PersonConfig(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:PersonConfig)
}
PersonConfig::PersonConfig(const PersonConfig& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  PersonConfig* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.desired_cash_on_hand_){nullptr}
    , decltype(_impl_.income_until_retirement_){nullptr}
    , decltype(_impl_.initial_yearly_expenses_){nullptr}
    , decltype(_impl_.medical_event_){nullptr}
    , decltype(_impl_.starting_money_){nullptr}
    , decltype(_impl_.current_age_){}
    , decltype(_impl_.death_age_){}
    , decltype(_impl_.retirement_age_){}
    , decltype(_impl_.stock_bond_ratio_){}
    , decltype(_impl_.yearly_raise_percent_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_desired_cash_on_hand()) {
    _this->_impl_.desired_cash_on_hand_ = new ::Money(*from._impl_.desired_cash_on_hand_);
  }
  if (from._internal_has_income_until_retirement()) {
    _this->_impl_.income_until_retirement_ = new ::Money(*from._impl_.income_until_retirement_);
  }
  if (from._internal_has_initial_yearly_expenses()) {
    _this->_impl_.initial_yearly_expenses_ = new ::Money(*from._impl_.initial_yearly_expenses_);
  }
  if (from._internal_has_medical_event()) {
    _this->_impl_.medical_event_ = new ::Event(*from._impl_.medical_event_);
  }
  if (from._internal_has_starting_money()) {
    _this->_impl_.starting_money_ = new ::Money(*from._impl_.starting_money_);
  }
  ::memcpy(&_impl_.current_age_, &from._impl_.current_age_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.yearly_raise_percent_) -
    reinterpret_cast<char*>(&_impl_.current_age_)) + sizeof(_impl_.yearly_raise_percent_));
  // @@protoc_insertion_point(copy_constructor:PersonConfig)
}

inline void PersonConfig::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.desired_cash_on_hand_){nullptr}
    , decltype(_impl_.income_until_retirement_){nullptr}
    , decltype(_impl_.initial_yearly_expenses_){nullptr}
    , decltype(_impl_.medical_event_){nullptr}
    , decltype(_impl_.starting_money_){nullptr}
    , decltype(_impl_.current_age_){uint64_t{0u}}
    , decltype(_impl_.death_age_){uint64_t{0u}}
    , decltype(_impl_.retirement_age_){uint64_t{0u}}
    , decltype(_impl_.stock_bond_ratio_){0}
    , decltype(_impl_.yearly_raise_percent_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

PersonConfig::~PersonConfig() {
  // @@protoc_insertion_point(destructor:PersonConfig)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void PersonConfig::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.desired_cash_on_hand_;
  if (this != internal_default_instance()) delete _impl_.income_until_retirement_;
  if (this != internal_default_instance()) delete _impl_.initial_yearly_expenses_;
  if (this != internal_default_instance()) delete _impl_.medical_event_;
  if (this != internal_default_instance()) delete _impl_.starting_money_;
}

void PersonConfig::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void PersonConfig::Clear() {
// @@protoc_insertion_point(message_clear_start:PersonConfig)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.desired_cash_on_hand_ != nullptr) {
    delete _impl_.desired_cash_on_hand_;
  }
  _impl_.desired_cash_on_hand_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.income_until_retirement_ != nullptr) {
    delete _impl_.income_until_retirement_;
  }
  _impl_.income_until_retirement_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.initial_yearly_expenses_ != nullptr) {
    delete _impl_.initial_yearly_expenses_;
  }
  _impl_.initial_yearly_expenses_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.medical_event_ != nullptr) {
    delete _impl_.medical_event_;
  }
  _impl_.medical_event_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.starting_money_ != nullptr) {
    delete _impl_.starting_money_;
  }
  _impl_.starting_money_ = nullptr;
  ::memset(&_impl_.current_age_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.yearly_raise_percent_) -
      reinterpret_cast<char*>(&_impl_.current_age_)) + sizeof(_impl_.yearly_raise_percent_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PersonConfig::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint64 current_age = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.current_age_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint64 death_age = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.death_age_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .Money desired_cash_on_hand = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_desired_cash_on_hand(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .Money income_until_retirement = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr = ctx->ParseMessage(_internal_mutable_income_until_retirement(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .Money initial_yearly_expenses = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          ptr = ctx->ParseMessage(_internal_mutable_initial_yearly_expenses(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .Event medical_event = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 50)) {
          ptr = ctx->ParseMessage(_internal_mutable_medical_event(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint64 retirement_age = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 56)) {
          _impl_.retirement_age_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .Money starting_money = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 66)) {
          ptr = ctx->ParseMessage(_internal_mutable_starting_money(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // double stock_bond_ratio = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 73)) {
          _impl_.stock_bond_ratio_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // double yearly_raise_percent = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 81)) {
          _impl_.yearly_raise_percent_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* PersonConfig::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:PersonConfig)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 current_age = 1;
  if (this->_internal_current_age() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(1, this->_internal_current_age(), target);
  }

  // uint64 death_age = 2;
  if (this->_internal_death_age() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(2, this->_internal_death_age(), target);
  }

  // .Money desired_cash_on_hand = 3;
  if (this->_internal_has_desired_cash_on_hand()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, _Internal::desired_cash_on_hand(this),
        _Internal::desired_cash_on_hand(this).GetCachedSize(), target, stream);
  }

  // .Money income_until_retirement = 4;
  if (this->_internal_has_income_until_retirement()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(4, _Internal::income_until_retirement(this),
        _Internal::income_until_retirement(this).GetCachedSize(), target, stream);
  }

  // .Money initial_yearly_expenses = 5;
  if (this->_internal_has_initial_yearly_expenses()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(5, _Internal::initial_yearly_expenses(this),
        _Internal::initial_yearly_expenses(this).GetCachedSize(), target, stream);
  }

  // .Event medical_event = 6;
  if (this->_internal_has_medical_event()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(6, _Internal::medical_event(this),
        _Internal::medical_event(this).GetCachedSize(), target, stream);
  }

  // uint64 retirement_age = 7;
  if (this->_internal_retirement_age() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(7, this->_internal_retirement_age(), target);
  }

  // .Money starting_money = 8;
  if (this->_internal_has_starting_money()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(8, _Internal::starting_money(this),
        _Internal::starting_money(this).GetCachedSize(), target, stream);
  }

  // double stock_bond_ratio = 9;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_stock_bond_ratio = this->_internal_stock_bond_ratio();
  uint64_t raw_stock_bond_ratio;
  memcpy(&raw_stock_bond_ratio, &tmp_stock_bond_ratio, sizeof(tmp_stock_bond_ratio));
  if (raw_stock_bond_ratio != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(9, this->_internal_stock_bond_ratio(), target);
  }

  // double yearly_raise_percent = 10;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_yearly_raise_percent = this->_internal_yearly_raise_percent();
  uint64_t raw_yearly_raise_percent;
  memcpy(&raw_yearly_raise_percent, &tmp_yearly_raise_percent, sizeof(tmp_yearly_raise_percent));
  if (raw_yearly_raise_percent != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(10, this->_internal_yearly_raise_percent(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PersonConfig)
  return target;
}

size_t PersonConfig::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:PersonConfig)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .Money desired_cash_on_hand = 3;
  if (this->_internal_has_desired_cash_on_hand()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.desired_cash_on_hand_);
  }

  // .Money income_until_retirement = 4;
  if (this->_internal_has_income_until_retirement()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.income_until_retirement_);
  }

  // .Money initial_yearly_expenses = 5;
  if (this->_internal_has_initial_yearly_expenses()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.initial_yearly_expenses_);
  }

  // .Event medical_event = 6;
  if (this->_internal_has_medical_event()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.medical_event_);
  }

  // .Money starting_money = 8;
  if (this->_internal_has_starting_money()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.starting_money_);
  }

  // uint64 current_age = 1;
  if (this->_internal_current_age() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_current_age());
  }

  // uint64 death_age = 2;
  if (this->_internal_death_age() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_death_age());
  }

  // uint64 retirement_age = 7;
  if (this->_internal_retirement_age() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_retirement_age());
  }

  // double stock_bond_ratio = 9;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_stock_bond_ratio = this->_internal_stock_bond_ratio();
  uint64_t raw_stock_bond_ratio;
  memcpy(&raw_stock_bond_ratio, &tmp_stock_bond_ratio, sizeof(tmp_stock_bond_ratio));
  if (raw_stock_bond_ratio != 0) {
    total_size += 1 + 8;
  }

  // double yearly_raise_percent = 10;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_yearly_raise_percent = this->_internal_yearly_raise_percent();
  uint64_t raw_yearly_raise_percent;
  memcpy(&raw_yearly_raise_percent, &tmp_yearly_raise_percent, sizeof(tmp_yearly_raise_percent));
  if (raw_yearly_raise_percent != 0) {
    total_size += 1 + 8;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PersonConfig::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    PersonConfig::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PersonConfig::GetClassData() const { return &_class_data_; }


void PersonConfig::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<PersonConfig*>(&to_msg);
  auto& from = static_cast<const PersonConfig&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:PersonConfig)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_desired_cash_on_hand()) {
    _this->_internal_mutable_desired_cash_on_hand()->::Money::MergeFrom(
        from._internal_desired_cash_on_hand());
  }
  if (from._internal_has_income_until_retirement()) {
    _this->_internal_mutable_income_until_retirement()->::Money::MergeFrom(
        from._internal_income_until_retirement());
  }
  if (from._internal_has_initial_yearly_expenses()) {
    _this->_internal_mutable_initial_yearly_expenses()->::Money::MergeFrom(
        from._internal_initial_yearly_expenses());
  }
  if (from._internal_has_medical_event()) {
    _this->_internal_mutable_medical_event()->::Event::MergeFrom(
        from._internal_medical_event());
  }
  if (from._internal_has_starting_money()) {
    _this->_internal_mutable_starting_money()->::Money::MergeFrom(
        from._internal_starting_money());
  }
  if (from._internal_current_age() != 0) {
    _this->_internal_set_current_age(from._internal_current_age());
  }
  if (from._internal_death_age() != 0) {
    _this->_internal_set_death_age(from._internal_death_age());
  }
  if (from._internal_retirement_age() != 0) {
    _this->_internal_set_retirement_age(from._internal_retirement_age());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_stock_bond_ratio = from._internal_stock_bond_ratio();
  uint64_t raw_stock_bond_ratio;
  memcpy(&raw_stock_bond_ratio, &tmp_stock_bond_ratio, sizeof(tmp_stock_bond_ratio));
  if (raw_stock_bond_ratio != 0) {
    _this->_internal_set_stock_bond_ratio(from._internal_stock_bond_ratio());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_yearly_raise_percent = from._internal_yearly_raise_percent();
  uint64_t raw_yearly_raise_percent;
  memcpy(&raw_yearly_raise_percent, &tmp_yearly_raise_percent, sizeof(tmp_yearly_raise_percent));
  if (raw_yearly_raise_percent != 0) {
    _this->_internal_set_yearly_raise_percent(from._internal_yearly_raise_percent());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PersonConfig::CopyFrom(const PersonConfig& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PersonConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PersonConfig::IsInitialized() const {
  return true;
}

void PersonConfig::InternalSwap(PersonConfig* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PersonConfig, _impl_.yearly_raise_percent_)
      + sizeof(PersonConfig::_impl_.yearly_raise_percent_)
      - PROTOBUF_FIELD_OFFSET(PersonConfig, _impl_.desired_cash_on_hand_)>(
          reinterpret_cast<char*>(&_impl_.desired_cash_on_hand_),
          reinterpret_cast<char*>(&other->_impl_.desired_cash_on_hand_));
}

::PROTOBUF_NAMESPACE_ID::Metadata PersonConfig::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_src_2fprotos_2fPersonConfig_2eproto_getter, &descriptor_table_src_2fprotos_2fPersonConfig_2eproto_once,
      file_level_metadata_src_2fprotos_2fPersonConfig_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::PersonConfig*
Arena::CreateMaybeMessage< ::PersonConfig >(Arena* arena) {
  return Arena::CreateMessageInternal< ::PersonConfig >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
