// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/protos/PersonConfig.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_src_2fprotos_2fPersonConfig_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_src_2fprotos_2fPersonConfig_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "src/protos/Money.pb.h"
#include "src/protos/Event.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_src_2fprotos_2fPersonConfig_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_src_2fprotos_2fPersonConfig_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_src_2fprotos_2fPersonConfig_2eproto;
class PersonConfig;
struct PersonConfigDefaultTypeInternal;
extern PersonConfigDefaultTypeInternal _PersonConfig_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::PersonConfig* Arena::CreateMaybeMessage<::PersonConfig>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class PersonConfig final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:PersonConfig) */ {
 public:
  inline PersonConfig() : PersonConfig(nullptr) {}
  ~PersonConfig() override;
  explicit PROTOBUF_CONSTEXPR PersonConfig(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PersonConfig(const PersonConfig& from);
  PersonConfig(PersonConfig&& from) noexcept
    : PersonConfig() {
    *this = ::std::move(from);
  }

  inline PersonConfig& operator=(const PersonConfig& from) {
    CopyFrom(from);
    return *this;
  }
  inline PersonConfig& operator=(PersonConfig&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PersonConfig& default_instance() {
    return *internal_default_instance();
  }
  static inline const PersonConfig* internal_default_instance() {
    return reinterpret_cast<const PersonConfig*>(
               &_PersonConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(PersonConfig& a, PersonConfig& b) {
    a.Swap(&b);
  }
  inline void Swap(PersonConfig* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PersonConfig* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PersonConfig* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PersonConfig>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PersonConfig& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PersonConfig& from) {
    PersonConfig::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PersonConfig* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PersonConfig";
  }
  protected:
  explicit PersonConfig(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDesiredCashOnHandFieldNumber = 3,
    kIncomeUntilRetirementFieldNumber = 4,
    kInitialYearlyExpensesFieldNumber = 5,
    kMedicalEventFieldNumber = 6,
    kStartingMoneyFieldNumber = 8,
    kCurrentAgeFieldNumber = 1,
    kDeathAgeFieldNumber = 2,
    kRetirementAgeFieldNumber = 7,
    kStockBondRatioFieldNumber = 9,
    kYearlyRaisePercentFieldNumber = 10,
  };
  // .Money desired_cash_on_hand = 3;
  bool has_desired_cash_on_hand() const;
  private:
  bool _internal_has_desired_cash_on_hand() const;
  public:
  void clear_desired_cash_on_hand();
  const ::Money& desired_cash_on_hand() const;
  PROTOBUF_NODISCARD ::Money* release_desired_cash_on_hand();
  ::Money* mutable_desired_cash_on_hand();
  void set_allocated_desired_cash_on_hand(::Money* desired_cash_on_hand);
  private:
  const ::Money& _internal_desired_cash_on_hand() const;
  ::Money* _internal_mutable_desired_cash_on_hand();
  public:
  void unsafe_arena_set_allocated_desired_cash_on_hand(
      ::Money* desired_cash_on_hand);
  ::Money* unsafe_arena_release_desired_cash_on_hand();

  // .Money income_until_retirement = 4;
  bool has_income_until_retirement() const;
  private:
  bool _internal_has_income_until_retirement() const;
  public:
  void clear_income_until_retirement();
  const ::Money& income_until_retirement() const;
  PROTOBUF_NODISCARD ::Money* release_income_until_retirement();
  ::Money* mutable_income_until_retirement();
  void set_allocated_income_until_retirement(::Money* income_until_retirement);
  private:
  const ::Money& _internal_income_until_retirement() const;
  ::Money* _internal_mutable_income_until_retirement();
  public:
  void unsafe_arena_set_allocated_income_until_retirement(
      ::Money* income_until_retirement);
  ::Money* unsafe_arena_release_income_until_retirement();

  // .Money initial_yearly_expenses = 5;
  bool has_initial_yearly_expenses() const;
  private:
  bool _internal_has_initial_yearly_expenses() const;
  public:
  void clear_initial_yearly_expenses();
  const ::Money& initial_yearly_expenses() const;
  PROTOBUF_NODISCARD ::Money* release_initial_yearly_expenses();
  ::Money* mutable_initial_yearly_expenses();
  void set_allocated_initial_yearly_expenses(::Money* initial_yearly_expenses);
  private:
  const ::Money& _internal_initial_yearly_expenses() const;
  ::Money* _internal_mutable_initial_yearly_expenses();
  public:
  void unsafe_arena_set_allocated_initial_yearly_expenses(
      ::Money* initial_yearly_expenses);
  ::Money* unsafe_arena_release_initial_yearly_expenses();

  // .Event medical_event = 6;
  bool has_medical_event() const;
  private:
  bool _internal_has_medical_event() const;
  public:
  void clear_medical_event();
  const ::Event& medical_event() const;
  PROTOBUF_NODISCARD ::Event* release_medical_event();
  ::Event* mutable_medical_event();
  void set_allocated_medical_event(::Event* medical_event);
  private:
  const ::Event& _internal_medical_event() const;
  ::Event* _internal_mutable_medical_event();
  public:
  void unsafe_arena_set_allocated_medical_event(
      ::Event* medical_event);
  ::Event* unsafe_arena_release_medical_event();

  // .Money starting_money = 8;
  bool has_starting_money() const;
  private:
  bool _internal_has_starting_money() const;
  public:
  void clear_starting_money();
  const ::Money& starting_money() const;
  PROTOBUF_NODISCARD ::Money* release_starting_money();
  ::Money* mutable_starting_money();
  void set_allocated_starting_money(::Money* starting_money);
  private:
  const ::Money& _internal_starting_money() const;
  ::Money* _internal_mutable_starting_money();
  public:
  void unsafe_arena_set_allocated_starting_money(
      ::Money* starting_money);
  ::Money* unsafe_arena_release_starting_money();

  // uint64 current_age = 1;
  void clear_current_age();
  uint64_t current_age() const;
  void set_current_age(uint64_t value);
  private:
  uint64_t _internal_current_age() const;
  void _internal_set_current_age(uint64_t value);
  public:

  // uint64 death_age = 2;
  void clear_death_age();
  uint64_t death_age() const;
  void set_death_age(uint64_t value);
  private:
  uint64_t _internal_death_age() const;
  void _internal_set_death_age(uint64_t value);
  public:

  // uint64 retirement_age = 7;
  void clear_retirement_age();
  uint64_t retirement_age() const;
  void set_retirement_age(uint64_t value);
  private:
  uint64_t _internal_retirement_age() const;
  void _internal_set_retirement_age(uint64_t value);
  public:

  // double stock_bond_ratio = 9;
  void clear_stock_bond_ratio();
  double stock_bond_ratio() const;
  void set_stock_bond_ratio(double value);
  private:
  double _internal_stock_bond_ratio() const;
  void _internal_set_stock_bond_ratio(double value);
  public:

  // double yearly_raise_percent = 10;
  void clear_yearly_raise_percent();
  double yearly_raise_percent() const;
  void set_yearly_raise_percent(double value);
  private:
  double _internal_yearly_raise_percent() const;
  void _internal_set_yearly_raise_percent(double value);
  public:

  // @@protoc_insertion_point(class_scope:PersonConfig)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::Money* desired_cash_on_hand_;
    ::Money* income_until_retirement_;
    ::Money* initial_yearly_expenses_;
    ::Event* medical_event_;
    ::Money* starting_money_;
    uint64_t current_age_;
    uint64_t death_age_;
    uint64_t retirement_age_;
    double stock_bond_ratio_;
    double yearly_raise_percent_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_src_2fprotos_2fPersonConfig_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PersonConfig

// uint64 current_age = 1;
inline void PersonConfig::clear_current_age() {
  _impl_.current_age_ = uint64_t{0u};
}
inline uint64_t PersonConfig::_internal_current_age() const {
  return _impl_.current_age_;
}
inline uint64_t PersonConfig::current_age() const {
  // @@protoc_insertion_point(field_get:PersonConfig.current_age)
  return _internal_current_age();
}
inline void PersonConfig::_internal_set_current_age(uint64_t value) {
  
  _impl_.current_age_ = value;
}
inline void PersonConfig::set_current_age(uint64_t value) {
  _internal_set_current_age(value);
  // @@protoc_insertion_point(field_set:PersonConfig.current_age)
}

// uint64 death_age = 2;
inline void PersonConfig::clear_death_age() {
  _impl_.death_age_ = uint64_t{0u};
}
inline uint64_t PersonConfig::_internal_death_age() const {
  return _impl_.death_age_;
}
inline uint64_t PersonConfig::death_age() const {
  // @@protoc_insertion_point(field_get:PersonConfig.death_age)
  return _internal_death_age();
}
inline void PersonConfig::_internal_set_death_age(uint64_t value) {
  
  _impl_.death_age_ = value;
}
inline void PersonConfig::set_death_age(uint64_t value) {
  _internal_set_death_age(value);
  // @@protoc_insertion_point(field_set:PersonConfig.death_age)
}

// .Money desired_cash_on_hand = 3;
inline bool PersonConfig::_internal_has_desired_cash_on_hand() const {
  return this != internal_default_instance() && _impl_.desired_cash_on_hand_ != nullptr;
}
inline bool PersonConfig::has_desired_cash_on_hand() const {
  return _internal_has_desired_cash_on_hand();
}
inline const ::Money& PersonConfig::_internal_desired_cash_on_hand() const {
  const ::Money* p = _impl_.desired_cash_on_hand_;
  return p != nullptr ? *p : reinterpret_cast<const ::Money&>(
      ::_Money_default_instance_);
}
inline const ::Money& PersonConfig::desired_cash_on_hand() const {
  // @@protoc_insertion_point(field_get:PersonConfig.desired_cash_on_hand)
  return _internal_desired_cash_on_hand();
}
inline void PersonConfig::unsafe_arena_set_allocated_desired_cash_on_hand(
    ::Money* desired_cash_on_hand) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.desired_cash_on_hand_);
  }
  _impl_.desired_cash_on_hand_ = desired_cash_on_hand;
  if (desired_cash_on_hand) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:PersonConfig.desired_cash_on_hand)
}
inline ::Money* PersonConfig::release_desired_cash_on_hand() {
  
  ::Money* temp = _impl_.desired_cash_on_hand_;
  _impl_.desired_cash_on_hand_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::Money* PersonConfig::unsafe_arena_release_desired_cash_on_hand() {
  // @@protoc_insertion_point(field_release:PersonConfig.desired_cash_on_hand)
  
  ::Money* temp = _impl_.desired_cash_on_hand_;
  _impl_.desired_cash_on_hand_ = nullptr;
  return temp;
}
inline ::Money* PersonConfig::_internal_mutable_desired_cash_on_hand() {
  
  if (_impl_.desired_cash_on_hand_ == nullptr) {
    auto* p = CreateMaybeMessage<::Money>(GetArenaForAllocation());
    _impl_.desired_cash_on_hand_ = p;
  }
  return _impl_.desired_cash_on_hand_;
}
inline ::Money* PersonConfig::mutable_desired_cash_on_hand() {
  ::Money* _msg = _internal_mutable_desired_cash_on_hand();
  // @@protoc_insertion_point(field_mutable:PersonConfig.desired_cash_on_hand)
  return _msg;
}
inline void PersonConfig::set_allocated_desired_cash_on_hand(::Money* desired_cash_on_hand) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.desired_cash_on_hand_);
  }
  if (desired_cash_on_hand) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(desired_cash_on_hand));
    if (message_arena != submessage_arena) {
      desired_cash_on_hand = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, desired_cash_on_hand, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.desired_cash_on_hand_ = desired_cash_on_hand;
  // @@protoc_insertion_point(field_set_allocated:PersonConfig.desired_cash_on_hand)
}

// .Money income_until_retirement = 4;
inline bool PersonConfig::_internal_has_income_until_retirement() const {
  return this != internal_default_instance() && _impl_.income_until_retirement_ != nullptr;
}
inline bool PersonConfig::has_income_until_retirement() const {
  return _internal_has_income_until_retirement();
}
inline const ::Money& PersonConfig::_internal_income_until_retirement() const {
  const ::Money* p = _impl_.income_until_retirement_;
  return p != nullptr ? *p : reinterpret_cast<const ::Money&>(
      ::_Money_default_instance_);
}
inline const ::Money& PersonConfig::income_until_retirement() const {
  // @@protoc_insertion_point(field_get:PersonConfig.income_until_retirement)
  return _internal_income_until_retirement();
}
inline void PersonConfig::unsafe_arena_set_allocated_income_until_retirement(
    ::Money* income_until_retirement) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.income_until_retirement_);
  }
  _impl_.income_until_retirement_ = income_until_retirement;
  if (income_until_retirement) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:PersonConfig.income_until_retirement)
}
inline ::Money* PersonConfig::release_income_until_retirement() {
  
  ::Money* temp = _impl_.income_until_retirement_;
  _impl_.income_until_retirement_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::Money* PersonConfig::unsafe_arena_release_income_until_retirement() {
  // @@protoc_insertion_point(field_release:PersonConfig.income_until_retirement)
  
  ::Money* temp = _impl_.income_until_retirement_;
  _impl_.income_until_retirement_ = nullptr;
  return temp;
}
inline ::Money* PersonConfig::_internal_mutable_income_until_retirement() {
  
  if (_impl_.income_until_retirement_ == nullptr) {
    auto* p = CreateMaybeMessage<::Money>(GetArenaForAllocation());
    _impl_.income_until_retirement_ = p;
  }
  return _impl_.income_until_retirement_;
}
inline ::Money* PersonConfig::mutable_income_until_retirement() {
  ::Money* _msg = _internal_mutable_income_until_retirement();
  // @@protoc_insertion_point(field_mutable:PersonConfig.income_until_retirement)
  return _msg;
}
inline void PersonConfig::set_allocated_income_until_retirement(::Money* income_until_retirement) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.income_until_retirement_);
  }
  if (income_until_retirement) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(income_until_retirement));
    if (message_arena != submessage_arena) {
      income_until_retirement = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, income_until_retirement, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.income_until_retirement_ = income_until_retirement;
  // @@protoc_insertion_point(field_set_allocated:PersonConfig.income_until_retirement)
}

// .Money initial_yearly_expenses = 5;
inline bool PersonConfig::_internal_has_initial_yearly_expenses() const {
  return this != internal_default_instance() && _impl_.initial_yearly_expenses_ != nullptr;
}
inline bool PersonConfig::has_initial_yearly_expenses() const {
  return _internal_has_initial_yearly_expenses();
}
inline const ::Money& PersonConfig::_internal_initial_yearly_expenses() const {
  const ::Money* p = _impl_.initial_yearly_expenses_;
  return p != nullptr ? *p : reinterpret_cast<const ::Money&>(
      ::_Money_default_instance_);
}
inline const ::Money& PersonConfig::initial_yearly_expenses() const {
  // @@protoc_insertion_point(field_get:PersonConfig.initial_yearly_expenses)
  return _internal_initial_yearly_expenses();
}
inline void PersonConfig::unsafe_arena_set_allocated_initial_yearly_expenses(
    ::Money* initial_yearly_expenses) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.initial_yearly_expenses_);
  }
  _impl_.initial_yearly_expenses_ = initial_yearly_expenses;
  if (initial_yearly_expenses) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:PersonConfig.initial_yearly_expenses)
}
inline ::Money* PersonConfig::release_initial_yearly_expenses() {
  
  ::Money* temp = _impl_.initial_yearly_expenses_;
  _impl_.initial_yearly_expenses_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::Money* PersonConfig::unsafe_arena_release_initial_yearly_expenses() {
  // @@protoc_insertion_point(field_release:PersonConfig.initial_yearly_expenses)
  
  ::Money* temp = _impl_.initial_yearly_expenses_;
  _impl_.initial_yearly_expenses_ = nullptr;
  return temp;
}
inline ::Money* PersonConfig::_internal_mutable_initial_yearly_expenses() {
  
  if (_impl_.initial_yearly_expenses_ == nullptr) {
    auto* p = CreateMaybeMessage<::Money>(GetArenaForAllocation());
    _impl_.initial_yearly_expenses_ = p;
  }
  return _impl_.initial_yearly_expenses_;
}
inline ::Money* PersonConfig::mutable_initial_yearly_expenses() {
  ::Money* _msg = _internal_mutable_initial_yearly_expenses();
  // @@protoc_insertion_point(field_mutable:PersonConfig.initial_yearly_expenses)
  return _msg;
}
inline void PersonConfig::set_allocated_initial_yearly_expenses(::Money* initial_yearly_expenses) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.initial_yearly_expenses_);
  }
  if (initial_yearly_expenses) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(initial_yearly_expenses));
    if (message_arena != submessage_arena) {
      initial_yearly_expenses = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, initial_yearly_expenses, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.initial_yearly_expenses_ = initial_yearly_expenses;
  // @@protoc_insertion_point(field_set_allocated:PersonConfig.initial_yearly_expenses)
}

// .Event medical_event = 6;
inline bool PersonConfig::_internal_has_medical_event() const {
  return this != internal_default_instance() && _impl_.medical_event_ != nullptr;
}
inline bool PersonConfig::has_medical_event() const {
  return _internal_has_medical_event();
}
inline const ::Event& PersonConfig::_internal_medical_event() const {
  const ::Event* p = _impl_.medical_event_;
  return p != nullptr ? *p : reinterpret_cast<const ::Event&>(
      ::_Event_default_instance_);
}
inline const ::Event& PersonConfig::medical_event() const {
  // @@protoc_insertion_point(field_get:PersonConfig.medical_event)
  return _internal_medical_event();
}
inline void PersonConfig::unsafe_arena_set_allocated_medical_event(
    ::Event* medical_event) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.medical_event_);
  }
  _impl_.medical_event_ = medical_event;
  if (medical_event) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:PersonConfig.medical_event)
}
inline ::Event* PersonConfig::release_medical_event() {
  
  ::Event* temp = _impl_.medical_event_;
  _impl_.medical_event_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::Event* PersonConfig::unsafe_arena_release_medical_event() {
  // @@protoc_insertion_point(field_release:PersonConfig.medical_event)
  
  ::Event* temp = _impl_.medical_event_;
  _impl_.medical_event_ = nullptr;
  return temp;
}
inline ::Event* PersonConfig::_internal_mutable_medical_event() {
  
  if (_impl_.medical_event_ == nullptr) {
    auto* p = CreateMaybeMessage<::Event>(GetArenaForAllocation());
    _impl_.medical_event_ = p;
  }
  return _impl_.medical_event_;
}
inline ::Event* PersonConfig::mutable_medical_event() {
  ::Event* _msg = _internal_mutable_medical_event();
  // @@protoc_insertion_point(field_mutable:PersonConfig.medical_event)
  return _msg;
}
inline void PersonConfig::set_allocated_medical_event(::Event* medical_event) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.medical_event_);
  }
  if (medical_event) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(medical_event));
    if (message_arena != submessage_arena) {
      medical_event = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, medical_event, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.medical_event_ = medical_event;
  // @@protoc_insertion_point(field_set_allocated:PersonConfig.medical_event)
}

// uint64 retirement_age = 7;
inline void PersonConfig::clear_retirement_age() {
  _impl_.retirement_age_ = uint64_t{0u};
}
inline uint64_t PersonConfig::_internal_retirement_age() const {
  return _impl_.retirement_age_;
}
inline uint64_t PersonConfig::retirement_age() const {
  // @@protoc_insertion_point(field_get:PersonConfig.retirement_age)
  return _internal_retirement_age();
}
inline void PersonConfig::_internal_set_retirement_age(uint64_t value) {
  
  _impl_.retirement_age_ = value;
}
inline void PersonConfig::set_retirement_age(uint64_t value) {
  _internal_set_retirement_age(value);
  // @@protoc_insertion_point(field_set:PersonConfig.retirement_age)
}

// .Money starting_money = 8;
inline bool PersonConfig::_internal_has_starting_money() const {
  return this != internal_default_instance() && _impl_.starting_money_ != nullptr;
}
inline bool PersonConfig::has_starting_money() const {
  return _internal_has_starting_money();
}
inline const ::Money& PersonConfig::_internal_starting_money() const {
  const ::Money* p = _impl_.starting_money_;
  return p != nullptr ? *p : reinterpret_cast<const ::Money&>(
      ::_Money_default_instance_);
}
inline const ::Money& PersonConfig::starting_money() const {
  // @@protoc_insertion_point(field_get:PersonConfig.starting_money)
  return _internal_starting_money();
}
inline void PersonConfig::unsafe_arena_set_allocated_starting_money(
    ::Money* starting_money) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.starting_money_);
  }
  _impl_.starting_money_ = starting_money;
  if (starting_money) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:PersonConfig.starting_money)
}
inline ::Money* PersonConfig::release_starting_money() {
  
  ::Money* temp = _impl_.starting_money_;
  _impl_.starting_money_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::Money* PersonConfig::unsafe_arena_release_starting_money() {
  // @@protoc_insertion_point(field_release:PersonConfig.starting_money)
  
  ::Money* temp = _impl_.starting_money_;
  _impl_.starting_money_ = nullptr;
  return temp;
}
inline ::Money* PersonConfig::_internal_mutable_starting_money() {
  
  if (_impl_.starting_money_ == nullptr) {
    auto* p = CreateMaybeMessage<::Money>(GetArenaForAllocation());
    _impl_.starting_money_ = p;
  }
  return _impl_.starting_money_;
}
inline ::Money* PersonConfig::mutable_starting_money() {
  ::Money* _msg = _internal_mutable_starting_money();
  // @@protoc_insertion_point(field_mutable:PersonConfig.starting_money)
  return _msg;
}
inline void PersonConfig::set_allocated_starting_money(::Money* starting_money) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.starting_money_);
  }
  if (starting_money) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(starting_money));
    if (message_arena != submessage_arena) {
      starting_money = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, starting_money, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.starting_money_ = starting_money;
  // @@protoc_insertion_point(field_set_allocated:PersonConfig.starting_money)
}

// double stock_bond_ratio = 9;
inline void PersonConfig::clear_stock_bond_ratio() {
  _impl_.stock_bond_ratio_ = 0;
}
inline double PersonConfig::_internal_stock_bond_ratio() const {
  return _impl_.stock_bond_ratio_;
}
inline double PersonConfig::stock_bond_ratio() const {
  // @@protoc_insertion_point(field_get:PersonConfig.stock_bond_ratio)
  return _internal_stock_bond_ratio();
}
inline void PersonConfig::_internal_set_stock_bond_ratio(double value) {
  
  _impl_.stock_bond_ratio_ = value;
}
inline void PersonConfig::set_stock_bond_ratio(double value) {
  _internal_set_stock_bond_ratio(value);
  // @@protoc_insertion_point(field_set:PersonConfig.stock_bond_ratio)
}

// double yearly_raise_percent = 10;
inline void PersonConfig::clear_yearly_raise_percent() {
  _impl_.yearly_raise_percent_ = 0;
}
inline double PersonConfig::_internal_yearly_raise_percent() const {
  return _impl_.yearly_raise_percent_;
}
inline double PersonConfig::yearly_raise_percent() const {
  // @@protoc_insertion_point(field_get:PersonConfig.yearly_raise_percent)
  return _internal_yearly_raise_percent();
}
inline void PersonConfig::_internal_set_yearly_raise_percent(double value) {
  
  _impl_.yearly_raise_percent_ = value;
}
inline void PersonConfig::set_yearly_raise_percent(double value) {
  _internal_set_yearly_raise_percent(value);
  // @@protoc_insertion_point(field_set:PersonConfig.yearly_raise_percent)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_src_2fprotos_2fPersonConfig_2eproto
